export type ReasonKey = "rec" | "ctx" | "qua" | "top";

export type Moment = {
  id: string;
  kind: "shot" | "rally";
  type: string;
  speed: number | null;
  rallyLen: number;
  outcome: string;
  match: string;
  round: string;
  score: string;
  t: string;
  dur: number;
  ord: number;
  dotX: number;
  dotY: number;
  glow: string;
  ctx: string[];
  s: { rec: number; ctx: number; qua: number; top: number };
  title: string;
  reasons: { k: ReasonKey; label: string }[];
};

export const MOMENTS: Moment[] = [
  {
    id: "m1",
    kind: "shot",
    type: "Smash",
    speed: 312,
    rallyLen: 7,
    outcome: "winner",
    match: "Axelsen vs Momota",
    round: "Final",
    score: "18–16 · G3",
    t: "1:41:22",
    dur: 8,
    ord: 96,
    dotX: 62,
    dotY: 30,
    glow: "rgba(54,147,255,0.22)",
    ctx: [],
    s: { rec: 98, ctx: 60, qua: 82, top: 96 },
    title: "312 km/h smash — down the line",
    reasons: [
      { k: "rec", label: "Fastest in your library" },
      { k: "qua", label: "Clean framing" },
    ],
  },
  {
    id: "m2",
    kind: "rally",
    type: "Rally",
    speed: null,
    rallyLen: 26,
    outcome: "winner",
    match: "An Se-young vs Marín",
    round: "SF",
    score: "19–20 · G3",
    t: "0:58:41",
    dur: 34,
    ord: 92,
    dotX: 48,
    dotY: 62,
    glow: "rgba(45,212,167,0.2)",
    ctx: ["match point"],
    s: { rec: 90, ctx: 98, qua: 72, top: 93 },
    title: "26-shot rally to save match point",
    reasons: [
      { k: "ctx", label: "Saved match point · 19–20" },
      { k: "rec", label: "Longest rally this season" },
    ],
  },
  {
    id: "m3",
    kind: "shot",
    type: "Net",
    speed: null,
    rallyLen: 9,
    outcome: "winner",
    match: "Tai Tzu-ying vs Sindhu",
    round: "Group B",
    score: "20–20 · G3",
    t: "1:12:09",
    dur: 6,
    ord: 88,
    dotX: 38,
    dotY: 48,
    glow: "rgba(251,191,36,0.18)",
    ctx: ["decider"],
    s: { rec: 40, ctx: 93, qua: 66, top: 80 },
    title: "Net kill at 20–20 in the decider",
    reasons: [{ k: "ctx", label: "Decider · 20–20" }],
  },
  {
    id: "m4",
    kind: "shot",
    type: "Drop",
    speed: null,
    rallyLen: 11,
    outcome: "winner",
    match: "Lin vs Lee",
    round: "Exhibition",
    score: "11–8 · G2",
    t: "0:24:57",
    dur: 9,
    ord: 84,
    dotX: 70,
    dotY: 55,
    glow: "rgba(80,222,255,0.2)",
    ctx: [],
    s: { rec: 35, ctx: 40, qua: 92, top: 74 },
    title: "Cross-court drop winner",
    reasons: [{ k: "qua", label: "Crowd reaction · clean framing" }],
  },
  {
    id: "m5",
    kind: "shot",
    type: "Smash",
    speed: 304,
    rallyLen: 5,
    outcome: "winner",
    match: "Axelsen vs Momota",
    round: "Final",
    score: "9–7 · G1",
    t: "0:14:33",
    dur: 7,
    ord: 82,
    dotX: 55,
    dotY: 26,
    glow: "rgba(54,147,255,0.2)",
    ctx: [],
    s: { rec: 78, ctx: 45, qua: 70, top: 90 },
    title: "304 km/h smash off the lift",
    reasons: [
      { k: "top", label: "Top moment · Final" },
      { k: "rec", label: "2nd fastest this season" },
    ],
  },
  {
    id: "m6",
    kind: "rally",
    type: "Rally",
    speed: null,
    rallyLen: 17,
    outcome: "winner",
    match: "Antonsen vs Ginting",
    round: "QF",
    score: "15–17 · G2",
    t: "0:47:12",
    dur: 22,
    ord: 78,
    dotX: 44,
    dotY: 70,
    glow: "rgba(176,123,255,0.18)",
    ctx: ["comeback"],
    s: { rec: 55, ctx: 90, qua: 60, top: 78 },
    title: "The rally that flipped game 2",
    reasons: [{ k: "ctx", label: "Comeback · 5-point run started here" }],
  },
  {
    id: "m7",
    kind: "shot",
    type: "Drive",
    speed: 214,
    rallyLen: 13,
    outcome: "winner",
    match: "Christie vs L. Sen",
    round: "SF",
    score: "17–15 · G2",
    t: "1:02:48",
    dur: 12,
    ord: 74,
    dotX: 30,
    dotY: 58,
    glow: "rgba(80,222,255,0.18)",
    ctx: [],
    s: { rec: 45, ctx: 50, qua: 90, top: 76 },
    title: "Diving save into counter winner",
    reasons: [{ k: "qua", label: "Highlight-grade save" }],
  },
  {
    id: "m8",
    kind: "shot",
    type: "Net",
    speed: null,
    rallyLen: 8,
    outcome: "winner",
    match: "Kunlavut vs Popov",
    round: "QF",
    score: "13–11 · G1",
    t: "0:31:26",
    dur: 7,
    ord: 70,
    dotX: 52,
    dotY: 44,
    glow: "rgba(54,147,255,0.16)",
    ctx: [],
    s: { rec: 40, ctx: 42, qua: 84, top: 70 },
    title: "Hold-and-flick deception winner",
    reasons: [{ k: "qua", label: "Deception — clean look" }],
  },
  {
    id: "m9",
    kind: "rally",
    type: "Rally",
    speed: null,
    rallyLen: 18,
    outcome: "winner",
    match: "Shi Yu Qi vs Lee ZJ",
    round: "Final",
    score: "20–18 · G3",
    t: "1:19:54",
    dur: 24,
    ord: 66,
    dotX: 60,
    dotY: 66,
    glow: "rgba(45,212,167,0.18)",
    ctx: ["match point"],
    s: { rec: 62, ctx: 95, qua: 66, top: 88 },
    title: "18-shot rally to close the match",
    reasons: [{ k: "ctx", label: "Match point won" }],
  },
  {
    id: "m10",
    kind: "shot",
    type: "Clear",
    speed: null,
    rallyLen: 10,
    outcome: "winner",
    match: "Tai Tzu-ying vs Sindhu",
    round: "Group B",
    score: "15–13 · G2",
    t: "0:52:17",
    dur: 8,
    ord: 62,
    dotX: 66,
    dotY: 22,
    glow: "rgba(251,191,36,0.15)",
    ctx: [],
    s: { rec: 85, ctx: 38, qua: 58, top: 68 },
    title: "Backhand clear winner",
    reasons: [{ k: "rec", label: "Rare: 1 of 3 backhand winners ever" }],
  },
  {
    id: "m11",
    kind: "shot",
    type: "Drive",
    speed: 196,
    rallyLen: 12,
    outcome: "winner",
    match: "Christie vs L. Sen",
    round: "SF",
    score: "8–6 · G1",
    t: "0:18:05",
    dur: 10,
    ord: 58,
    dotX: 36,
    dotY: 40,
    glow: "rgba(244,81,92,0.15)",
    ctx: [],
    s: { rec: 40, ctx: 35, qua: 62, top: 58 },
    title: "Flat drive exchange — 8 in a row",
    reasons: [{ k: "qua", label: "Fast flat exchange" }],
  },
  {
    id: "m12",
    kind: "shot",
    type: "Smash",
    speed: 298,
    rallyLen: 6,
    outcome: "winner",
    match: "Antonsen vs Ginting",
    round: "QF",
    score: "19–16 · G3",
    t: "1:08:40",
    dur: 6,
    ord: 54,
    dotX: 58,
    dotY: 34,
    glow: "rgba(54,147,255,0.18)",
    ctx: [],
    s: { rec: 70, ctx: 44, qua: 58, top: 72 },
    title: "298 km/h smash at the body",
    reasons: [{ k: "rec", label: "Top-5 fastest this season" }],
  },
];
