export type Shot = { i: number; type: string; side: "FH" | "BH"; color: string; speed?: number };
export type Rally = {
  n: number;
  shots: number;
  dur: number;
  end: string;
  tone: "success" | "danger" | "warn";
  sequence: Shot[];
};

export const RALLIES: Rally[] = [
  {
    n: 1,
    shots: 4,
    dur: 6,
    end: "Net error",
    tone: "danger",
    sequence: [
      { i: 1, type: "Serve", side: "BH", color: "#3693ff" },
      { i: 2, type: "Net shot", side: "FH", color: "#2dd4a7" },
      { i: 3, type: "Net", side: "FH", color: "#2dd4a7" },
      { i: 4, type: "Net error", side: "BH", color: "#f4515c" },
    ],
  },
  {
    n: 2,
    shots: 7,
    dur: 11,
    end: "Smash",
    tone: "success",
    sequence: [
      { i: 1, type: "Serve", side: "FH", color: "#3693ff" },
      { i: 2, type: "Clear", side: "BH", color: "#3693ff" },
      { i: 3, type: "Drop", side: "FH", color: "#8b9cff" },
      { i: 4, type: "Lift", side: "FH", color: "#50deff" },
      { i: 5, type: "Clear", side: "BH", color: "#3693ff" },
      { i: 6, type: "Smash", side: "FH", color: "#f4515c", speed: 304 },
      { i: 7, type: "Block error", side: "BH", color: "#f4515c" },
    ],
  },
  {
    n: 3,
    shots: 12,
    dur: 18,
    end: "Drop winner",
    tone: "success",
    sequence: [
      { i: 1, type: "Serve", side: "BH", color: "#3693ff" },
      { i: 2, type: "Drive", side: "FH", color: "#50deff" },
      { i: 3, type: "Drive", side: "BH", color: "#50deff" },
      { i: 4, type: "Lift", side: "FH", color: "#50deff" },
      { i: 5, type: "Smash", side: "FH", color: "#f4515c", speed: 298 },
      { i: 6, type: "Block", side: "FH", color: "#2dd4a7" },
      { i: 7, type: "Net", side: "BH", color: "#2dd4a7" },
      { i: 8, type: "Lift", side: "FH", color: "#50deff" },
      { i: 9, type: "Clear", side: "BH", color: "#3693ff" },
      { i: 10, type: "Drop", side: "FH", color: "#8b9cff" },
      { i: 11, type: "Net", side: "FH", color: "#2dd4a7" },
      { i: 12, type: "Drop winner", side: "BH", color: "#8b9cff" },
    ],
  },
  {
    n: 4,
    shots: 9,
    dur: 14,
    end: "Drive winner",
    tone: "success",
    sequence: [
      { i: 1, type: "Serve", side: "FH", color: "#3693ff" },
      { i: 2, type: "Net", side: "FH", color: "#2dd4a7" },
      { i: 3, type: "Lift", side: "BH", color: "#50deff" },
      { i: 4, type: "Smash", side: "FH", color: "#f4515c", speed: 311 },
      { i: 5, type: "Block", side: "BH", color: "#2dd4a7" },
      { i: 6, type: "Drive", side: "FH", color: "#50deff" },
      { i: 7, type: "Drive", side: "BH", color: "#50deff" },
      { i: 8, type: "Drive", side: "FH", color: "#50deff" },
      { i: 9, type: "Drive winner", side: "BH", color: "#50deff" },
    ],
  },
  {
    n: 5,
    shots: 18,
    dur: 27,
    end: "Smash",
    tone: "success",
    sequence: [
      { i: 1, type: "Serve", side: "BH", color: "#3693ff" },
      { i: 2, type: "Clear", side: "FH", color: "#3693ff" },
      { i: 3, type: "Clear", side: "BH", color: "#3693ff" },
      { i: 4, type: "Drop", side: "FH", color: "#8b9cff" },
      { i: 5, type: "Net", side: "FH", color: "#2dd4a7" },
      { i: 6, type: "Lift", side: "BH", color: "#50deff" },
      { i: 7, type: "Smash", side: "FH", color: "#f4515c", speed: 318 },
      { i: 8, type: "Block", side: "FH", color: "#2dd4a7" },
      { i: 9, type: "Net", side: "BH", color: "#2dd4a7" },
      { i: 10, type: "Lift", side: "FH", color: "#50deff" },
      { i: 11, type: "Clear", side: "BH", color: "#3693ff" },
      { i: 12, type: "Drop", side: "FH", color: "#8b9cff" },
      { i: 13, type: "Lift", side: "BH", color: "#50deff" },
      { i: 14, type: "Smash", side: "FH", color: "#f4515c", speed: 322 },
      { i: 15, type: "Block", side: "BH", color: "#2dd4a7" },
      { i: 16, type: "Drive", side: "FH", color: "#50deff" },
      { i: 17, type: "Lift", side: "BH", color: "#50deff" },
      { i: 18, type: "Smash", side: "FH", color: "#f4515c", speed: 328 },
    ],
  },
  {
    n: 6,
    shots: 6,
    dur: 9,
    end: "Net kill",
    tone: "success",
    sequence: [
      { i: 1, type: "Serve", side: "FH", color: "#3693ff" },
      { i: 2, type: "Net", side: "FH", color: "#2dd4a7" },
      { i: 3, type: "Net", side: "BH", color: "#2dd4a7" },
      { i: 4, type: "Lift", side: "FH", color: "#50deff" },
      { i: 5, type: "Drop", side: "BH", color: "#8b9cff" },
      { i: 6, type: "Net kill", side: "FH", color: "#2dd4a7" },
    ],
  },
  {
    n: 7,
    shots: 14,
    dur: 21,
    end: "Smash",
    tone: "success",
    sequence: [
      { i: 1, type: "Serve", side: "BH", color: "#3693ff" },
      { i: 2, type: "Net shot", side: "FH", color: "#2dd4a7" },
      { i: 3, type: "Lift", side: "BH", color: "#50deff" },
      { i: 4, type: "Clear", side: "FH", color: "#3693ff" },
      { i: 5, type: "Drop", side: "BH", color: "#8b9cff" },
      { i: 6, type: "Net", side: "FH", color: "#2dd4a7" },
      { i: 7, type: "Lift", side: "BH", color: "#50deff" },
      { i: 8, type: "Smash", side: "FH", color: "#f4515c", speed: 308 },
      { i: 9, type: "Block", side: "FH", color: "#2dd4a7" },
      { i: 10, type: "Drive", side: "BH", color: "#50deff" },
      { i: 11, type: "Lift", side: "FH", color: "#50deff" },
      { i: 12, type: "Clear", side: "BH", color: "#3693ff" },
      { i: 13, type: "Drop", side: "FH", color: "#8b9cff" },
      { i: 14, type: "Smash", side: "BH", color: "#f4515c", speed: 316 },
    ],
  },
  {
    n: 8,
    shots: 8,
    dur: 12,
    end: "Unforced",
    tone: "danger",
    sequence: [
      { i: 1, type: "Serve", side: "FH", color: "#3693ff" },
      { i: 2, type: "Clear", side: "BH", color: "#3693ff" },
      { i: 3, type: "Drop", side: "FH", color: "#8b9cff" },
      { i: 4, type: "Lift", side: "BH", color: "#50deff" },
      { i: 5, type: "Smash", side: "FH", color: "#f4515c", speed: 301 },
      { i: 6, type: "Block", side: "BH", color: "#2dd4a7" },
      { i: 7, type: "Net", side: "FH", color: "#2dd4a7" },
      { i: 8, type: "Lift long", side: "BH", color: "#f4515c" },
    ],
  },
  {
    n: 9,
    shots: 5,
    dur: 8,
    end: "Smash",
    tone: "success",
    sequence: [
      { i: 1, type: "Serve", side: "BH", color: "#3693ff" },
      { i: 2, type: "Clear", side: "FH", color: "#3693ff" },
      { i: 3, type: "Clear", side: "BH", color: "#3693ff" },
      { i: 4, type: "Drop", side: "FH", color: "#8b9cff" },
      { i: 5, type: "Smash", side: "BH", color: "#f4515c", speed: 324 },
    ],
  },
];
