import { NextRequest, NextResponse } from 'next/server';
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';
// import { getUserVideos } from '@/lib/r2';

export const runtime = 'nodejs';

const r2Client = new S3Client({
  region: 'auto',
  endpoint: process.env.R2_ENDPOINT_URL,
  credentials: {
    accessKeyId: process.env.R2_ACCESS_KEY_ID!,
    secretAccessKey: process.env.R2_SECRET_ACCESS_KEY!,
  },
});

const BUCKET_NAME = process.env.R2_BUCKET_NAME!;

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const userId = searchParams.get('userId');
    const videoId = searchParams.get('videoId');

    if (!userId || !videoId) {
      return NextResponse.json(
        { error: 'Missing userId or videoId parameter' },
        { status: 400 }
      );
    }

    // Try to get court visualization first (generated by RunPod processing)
    const visualizationKey = `dev/${userId}/${videoId}/court_visualization.png`;
    try {
      const vizCommand = new GetObjectCommand({
        Bucket: BUCKET_NAME,
        Key: visualizationKey,
      });
      
      const vizResponse = await r2Client.send(vizCommand);
      
      if (vizResponse.Body) {
        const stream = vizResponse.Body as ReadableStream;
        return new NextResponse(stream, {
          headers: {
            'Content-Type': 'image/png',
            'Cache-Control': 'public, max-age=86400', // Cache for 1 day
          },
        });
      }
    } catch {
      // Court visualization doesn't exist, try frame instead
    }

    // Try to get existing court frame
    const frameKey = `dev/${userId}/${videoId}/court_frame.jpg`;
    try {
      const frameCommand = new GetObjectCommand({
        Bucket: BUCKET_NAME,
        Key: frameKey,
      });
      
      const frameResponse = await r2Client.send(frameCommand);
      
      if (frameResponse.Body) {
        const stream = frameResponse.Body as ReadableStream;
        return new NextResponse(stream, {
          headers: {
            'Content-Type': 'image/jpeg',
            'Cache-Control': 'public, max-age=86400', // Cache for 1 day
          },
        });
      }
    } catch {
      // Court frame doesn't exist, try thumbnail instead
    }

    // Fallback to thumbnail
    const thumbnailKey = `dev/${userId}/${videoId}/thumbnail.jpg`;
    
    try {
      const thumbnailCommand = new GetObjectCommand({
        Bucket: BUCKET_NAME,
        Key: thumbnailKey,
      });
      
      const thumbnailResponse = await r2Client.send(thumbnailCommand);
      
      if (thumbnailResponse.Body) {
        const stream = thumbnailResponse.Body as ReadableStream;
        return new NextResponse(stream, {
          headers: {
            'Content-Type': 'image/jpeg',
            'Cache-Control': 'public, max-age=86400', // Cache for 1 day
          },
        });
      }
    } catch (error) {
      console.log('Thumbnail not found at expected path:', error);
      // Thumbnail doesn't exist either, try to generate it
    }

    // Last resort: check for SVG placeholder from old thumbnail system
    const svgKey = `dev/${userId}/${videoId}/thumbnail.svg`;
    try {
      const svgCommand = new GetObjectCommand({
        Bucket: BUCKET_NAME,
        Key: svgKey,
      });
      
      const svgResponse = await r2Client.send(svgCommand);
      
      if (svgResponse.Body) {
        const stream = svgResponse.Body as ReadableStream;
        return new NextResponse(stream, {
          headers: {
            'Content-Type': 'image/svg+xml',
            'Cache-Control': 'public, max-age=86400',
          },
        });
      }
    } catch {
      // SVG placeholder doesn't exist either
    }

    // Absolutely no frame available - return 404
    return NextResponse.json(
      { 
        error: 'No court frame or thumbnail available. Use the "Regenerate Frame" button to create one.' 
      },
      { status: 404 }
    );

    // If all else fails, return 404
    return NextResponse.json(
      { error: 'Court frame not available. Please analyze the video first or try again later.' },
      { status: 404 }
    );

  } catch (error) {
    console.error('Error getting court frame:', error);
    return NextResponse.json(
      { error: 'Failed to get court frame' },
      { status: 500 }
    );
  }
}