import type { LibraryMatch, MatchSummary, PlayerStats } from "./types";

export const pipelineVideos: MatchSummary[] = [
  {
    id: "1",
    title: "Club finals — Court 2",
    players: "Koster vs Nguyen",
    event: "Velocity Club · MS",
    duration: "48:12",
    status: "analyzing",
    progress: 62,
    date: "Today",
    tags: ["singles", "1080p"],
  },
  {
    id: "2",
    title: "U19 sparring set",
    players: "Park / Lee vs Chen / Wu",
    event: "National Team · MD",
    duration: "36:40",
    status: "queued",
    date: "Today",
    tags: ["doubles"],
  },
];

export const recentVideos: MatchSummary[] = [
  {
    id: "3",
    title: "Axelsen vs Momota",
    players: "V. Axelsen vs K. Momota",
    event: "All England · MS SF",
    duration: "1:12:04",
    status: "ready",
    href: "/video-analysis",
    date: "Mon",
    tags: ["BWF", "MS"],
  },
  {
    id: "4",
    title: "League night — Court 1",
    players: "Koster vs Alvarez",
    event: "Velocity Club · MS",
    duration: "41:22",
    status: "ready",
    href: "/video-analysis",
    date: "Sun",
    tags: ["singles"],
  },
  {
    id: "5",
    title: "Training block B",
    players: "Squad · multi-rally",
    event: "Practice · mixed",
    duration: "22:08",
    status: "ready",
    href: "/video-analysis",
    date: "Sat",
    tags: ["drills"],
  },
];

export const libraryMatches: LibraryMatch[] = [
  {
    id: "m1",
    title: "Axelsen vs Momota",
    players: "Axelsen vs Momota",
    opponent: "Kento Momota",
    tournament: "All England · Final",
    event: "All England · Final",
    date: "12 Jun",
    ord: 220,
    status: "ready",
    win: true,
    score: "21–18, 21–16",
    shots: 312,
    size: "1.4 GB",
    duration: "41:20",
    dur: "41:20",
    durMin: 41,
  },
  {
    id: "m2",
    title: "An Se-young vs Marín",
    players: "An Se-young vs Marín",
    opponent: "Carolina Marín",
    tournament: "All England · SF",
    event: "All England · SF",
    date: "10 Jun",
    ord: 210,
    status: "ready",
    win: true,
    score: "21–14, 19–21, 21–17",
    shots: 248,
    size: "1.1 GB",
    duration: "33:05",
    dur: "33:05",
    durMin: 33,
  },
  {
    id: "m3",
    title: "Singles drills — session 14",
    players: "Training",
    opponent: "Training",
    tournament: "Velocity BC · Court 2",
    event: "Velocity BC · Court 2",
    date: "Today",
    ord: 999,
    status: "analyzing",
    win: null,
    score: "",
    shots: 0,
    size: "2.2 GB",
    duration: "—",
    dur: null,
    durMin: 0,
    progress: 64,
  },
  {
    id: "m4",
    title: "Tai Tzu-ying vs Sindhu",
    players: "Tai Tzu-ying vs Sindhu",
    opponent: "P.V. Sindhu",
    tournament: "Indonesia Open · Group B",
    event: "Indonesia Open · Group B",
    date: "03 Jun",
    ord: 160,
    status: "ready",
    win: false,
    score: "18–21, 21–23",
    shots: 274,
    size: "1.3 GB",
    duration: "38:12",
    dur: "38:12",
    durMin: 38,
  },
  {
    id: "m5",
    title: "Lin vs Lee — exhibition",
    players: "Lin vs Lee",
    opponent: "Lee Chong Wei",
    tournament: "Legends Exhibition",
    event: "Legends Exhibition",
    date: "01 Jun",
    ord: 150,
    status: "ready",
    win: true,
    score: "21–19, 21–19",
    shots: 356,
    size: "1.6 GB",
    duration: "46:51",
    dur: "46:51",
    durMin: 46,
  },
  {
    id: "m6",
    title: "Antonsen vs Ginting",
    players: "Antonsen vs Ginting",
    opponent: "Anthony Ginting",
    tournament: "Malaysia Masters · QF",
    event: "Malaysia Masters · QF",
    date: "28 May",
    ord: 140,
    status: "ready",
    win: false,
    score: "21–17, 15–21, 19–21",
    shots: 298,
    size: "1.5 GB",
    duration: "44:08",
    dur: "44:08",
    durMin: 44,
  },
  {
    id: "m7",
    title: "Footwork ladder — court 1",
    players: "Training",
    opponent: "Training",
    tournament: "Velocity BC · Drills",
    event: "Velocity BC · Drills",
    date: "26 May",
    ord: 130,
    status: "ready",
    win: null,
    score: "",
    shots: 92,
    size: "640 MB",
    duration: "14:22",
    dur: "14:22",
    durMin: 14,
  },
  {
    id: "m8",
    title: "Yamaguchi vs Chochuwong",
    players: "Yamaguchi vs Chochuwong",
    opponent: "Pornpawee Chochuwong",
    tournament: "Thailand Open · R16",
    event: "Thailand Open · R16",
    date: "21 May",
    ord: 110,
    status: "queued",
    win: null,
    score: "",
    shots: 0,
    size: "1.2 GB",
    duration: "36:40",
    dur: "36:40",
    durMin: 36,
  },
  {
    id: "m9",
    title: "Christie vs Lakshya Sen",
    players: "Christie vs Lakshya Sen",
    opponent: "Lakshya Sen",
    tournament: "Singapore Open · SF",
    event: "Singapore Open · SF",
    date: "18 May",
    ord: 100,
    status: "ready",
    win: true,
    score: "21–15, 21–18",
    shots: 261,
    size: "1.2 GB",
    duration: "34:55",
    dur: "34:55",
    durMin: 34,
  },
  {
    id: "m10",
    title: "Doubles set — Velocity pairs",
    players: "Internal",
    opponent: "Internal",
    tournament: "Velocity BC · Court 3",
    event: "Velocity BC · Court 3",
    date: "15 May",
    ord: 90,
    status: "ready",
    win: null,
    score: "",
    shots: 188,
    size: "980 MB",
    duration: "28:30",
    dur: "28:30",
    durMin: 28,
  },
  {
    id: "m11",
    title: "Kunlavut vs Popov",
    players: "Kunlavut vs Popov",
    opponent: "Christo Popov",
    tournament: "French Open · QF",
    event: "French Open · QF",
    date: "11 May",
    ord: 80,
    status: "ready",
    win: true,
    score: "21–12, 21–19",
    shots: 233,
    size: "1.1 GB",
    duration: "31:12",
    dur: "31:12",
    durMin: 31,
  },
  {
    id: "m12",
    title: "Shi Yu Qi vs Lee Zii Jia",
    players: "Shi Yu Qi vs Lee Zii Jia",
    opponent: "Lee Zii Jia",
    tournament: "Asia Champ. · Final",
    event: "Asia Champ. · Final",
    date: "04 May",
    ord: 70,
    status: "ready",
    win: false,
    score: "21–18, 18–21, 17–21",
    shots: 341,
    size: "1.7 GB",
    duration: "49:40",
    dur: "49:40",
    durMin: 49,
  },
];

export const comparePlayers: Record<string, PlayerStats> = {
  viktor: {
    id: "viktor",
    name: "Viktor Koster",
    record: "24–9",
    winRate: 66,
    rally: 9.4,
    smash: 372,
    net: 71,
    attack: 58,
    errors: 7,
    mix: [24, 16, 15, 14],
  },
  momota: {
    id: "momota",
    name: "Kento Momota",
    record: "31–6",
    winRate: 71,
    rally: 11.2,
    smash: 348,
    net: 74,
    attack: 49,
    errors: 6,
    mix: [29, 14, 11, 12],
  },
  axelsen: {
    id: "axelsen",
    name: "Viktor Axelsen",
    record: "29–7",
    winRate: 69,
    rally: 8.6,
    smash: 388,
    net: 66,
    attack: 64,
    errors: 9,
    mix: [21, 17, 22, 10],
  },
  ansy: {
    id: "ansy",
    name: "An Se-young",
    record: "33–4",
    winRate: 78,
    rally: 10.4,
    smash: 332,
    net: 76,
    attack: 55,
    errors: 5,
    mix: [26, 18, 12, 15],
  },
  ginting: {
    id: "ginting",
    name: "Anthony Ginting",
    record: "22–12",
    winRate: 61,
    rally: 8.1,
    smash: 369,
    net: 63,
    attack: 67,
    errors: 11,
    mix: [19, 15, 25, 13],
  },
  sindhu: {
    id: "sindhu",
    name: "P.V. Sindhu",
    record: "20–13",
    winRate: 58,
    rally: 9.7,
    smash: 351,
    net: 60,
    attack: 61,
    errors: 12,
    mix: [23, 16, 19, 11],
  },
};
